/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CryptoTradingSimulatorRouteImport } from './routes/crypto-trading-simulator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DayTradingSimulatorRouteImport } from './routes/day-trading-simulator'
import { Route as ForexTradingSimulatorRouteImport } from './routes/forex-trading-simulator'
import { Route as IntradayTradingPracticeRouteImport } from './routes/intraday-trading-practice'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as MarketReplayRouteImport } from './routes/market-replay'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UserAgreementRouteImport } from './routes/user-agreement'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as pagesAboutRouteImport } from './routes/(pages)/about'
import { Route as pagesAiRouteImport } from './routes/(pages)/ai'
import { Route as pagesChangelogRouteImport } from './routes/(pages)/changelog'
import { Route as pagesContactRouteImport } from './routes/(pages)/contact'
import { Route as pagesPricingRouteImport } from './routes/(pages)/pricing'
import { Route as pagesRoadmapRouteImport } from './routes/(pages)/roadmap'
import { Route as pagesWaitlistRouteImport } from './routes/(pages)/waitlist'
import { Route as testsTest404RouteImport } from './routes/(tests)/test-404'
import { Route as testsTestErrorRouteImport } from './routes/(tests)/test-error'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiChartSettingsRouteImport } from './routes/api/chart-settings'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as GoSlugRouteImport } from './routes/go/$slug'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsFilesRouteImport } from './routes/settings/files'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsPaymentRouteImport } from './routes/settings/payment'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDayTradingDataSplatRouteImport } from './routes/api/day-trading-data/$'
import { Route as ApiE2eUsersRouteImport } from './routes/api/e2e/users'
import { Route as ApiPlayDataSplatRouteImport } from './routes/api/play-data/$'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiWebhooksCreemRouteImport } from './routes/api/webhooks/creem'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as BlogPPageRouteImport } from './routes/blog/p/$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoTradingSimulatorRoute = CryptoTradingSimulatorRouteImport.update({
  id: '/crypto-trading-simulator',
  path: '/crypto-trading-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DayTradingSimulatorRoute = DayTradingSimulatorRouteImport.update({
  id: '/day-trading-simulator',
  path: '/day-trading-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ForexTradingSimulatorRoute = ForexTradingSimulatorRouteImport.update({
  id: '/forex-trading-simulator',
  path: '/forex-trading-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const IntradayTradingPracticeRoute = IntradayTradingPracticeRouteImport.update({
  id: '/intraday-trading-practice',
  path: '/intraday-trading-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketReplayRoute = MarketReplayRouteImport.update({
  id: '/market-replay',
  path: '/market-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAgreementRoute = UserAgreementRouteImport.update({
  id: '/user-agreement',
  path: '/user-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAboutRoute = pagesAboutRouteImport.update({
  id: '/(pages)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAiRoute = pagesAiRouteImport.update({
  id: '/(pages)/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesChangelogRoute = pagesChangelogRouteImport.update({
  id: '/(pages)/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesContactRoute = pagesContactRouteImport.update({
  id: '/(pages)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesPricingRoute = pagesPricingRouteImport.update({
  id: '/(pages)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesRoadmapRoute = pagesRoadmapRouteImport.update({
  id: '/(pages)/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesWaitlistRoute = pagesWaitlistRouteImport.update({
  id: '/(pages)/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const testsTest404Route = testsTest404RouteImport.update({
  id: '/(tests)/test-404',
  path: '/test-404',
  getParentRoute: () => rootRouteImport,
} as any)
const testsTestErrorRoute = testsTestErrorRouteImport.update({
  id: '/(tests)/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChartSettingsRoute = ApiChartSettingsRouteImport.update({
  id: '/api/chart-settings',
  path: '/api/chart-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDayTradingDataSplatRoute = ApiDayTradingDataSplatRouteImport.update({
  id: '/api/day-trading-data/$',
  path: '/api/day-trading-data/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eUsersRoute = ApiE2eUsersRouteImport.update({
  id: '/api/e2e/users',
  path: '/api/e2e/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayDataSplatRoute = ApiPlayDataSplatRouteImport.update({
  id: '/api/play-data/$',
  path: '/api/play-data/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCreemRoute = ApiWebhooksCreemRouteImport.update({
  id: '/api/webhooks/creem',
  path: '/api/webhooks/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPPageRoute = BlogPPageRouteImport.update({
  id: '/blog/p/$page',
  path: '/blog/p/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/crypto-trading-simulator': typeof CryptoTradingSimulatorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/day-trading-simulator': typeof DayTradingSimulatorRoute
  '/forex-trading-simulator': typeof ForexTradingSimulatorRoute
  '/intraday-trading-practice': typeof IntradayTradingPracticeRoute
  '/languages': typeof LanguagesRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/market-replay': typeof MarketReplayRoute
  '/play': typeof PlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/user-agreement': typeof UserAgreementRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/ai': typeof pagesAiRoute
  '/changelog': typeof pagesChangelogRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/roadmap': typeof pagesRoadmapRoute
  '/waitlist': typeof pagesWaitlistRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chart-settings': typeof ApiChartSettingsRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/day-trading-data/$': typeof ApiDayTradingDataSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/play-data/$': typeof ApiPlayDataSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/blog/p/$page': typeof BlogPPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/crypto-trading-simulator': typeof CryptoTradingSimulatorRoute
  '/day-trading-simulator': typeof DayTradingSimulatorRoute
  '/forex-trading-simulator': typeof ForexTradingSimulatorRoute
  '/intraday-trading-practice': typeof IntradayTradingPracticeRoute
  '/languages': typeof LanguagesRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/market-replay': typeof MarketReplayRoute
  '/play': typeof PlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/user-agreement': typeof UserAgreementRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/ai': typeof pagesAiRoute
  '/changelog': typeof pagesChangelogRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/roadmap': typeof pagesRoadmapRoute
  '/waitlist': typeof pagesWaitlistRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chart-settings': typeof ApiChartSettingsRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/day-trading-data/$': typeof ApiDayTradingDataSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/play-data/$': typeof ApiPlayDataSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/blog/p/$page': typeof BlogPPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/crypto-trading-simulator': typeof CryptoTradingSimulatorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/day-trading-simulator': typeof DayTradingSimulatorRoute
  '/forex-trading-simulator': typeof ForexTradingSimulatorRoute
  '/intraday-trading-practice': typeof IntradayTradingPracticeRoute
  '/languages': typeof LanguagesRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/market-replay': typeof MarketReplayRoute
  '/play': typeof PlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/user-agreement': typeof UserAgreementRoute
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/(pages)/about': typeof pagesAboutRoute
  '/(pages)/ai': typeof pagesAiRoute
  '/(pages)/changelog': typeof pagesChangelogRoute
  '/(pages)/contact': typeof pagesContactRoute
  '/(pages)/pricing': typeof pagesPricingRoute
  '/(pages)/roadmap': typeof pagesRoadmapRoute
  '/(pages)/waitlist': typeof pagesWaitlistRoute
  '/(tests)/test-404': typeof testsTest404Route
  '/(tests)/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chart-settings': typeof ApiChartSettingsRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/day-trading-data/$': typeof ApiDayTradingDataSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/play-data/$': typeof ApiPlayDataSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/blog/p/$page': typeof BlogPPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/crypto-trading-simulator'
    | '/dashboard'
    | '/day-trading-simulator'
    | '/forex-trading-simulator'
    | '/intraday-trading-practice'
    | '/languages'
    | '/manifest.json'
    | '/market-replay'
    | '/play'
    | '/privacy-policy'
    | '/resources'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/user-agreement'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/ai'
    | '/changelog'
    | '/contact'
    | '/pricing'
    | '/roadmap'
    | '/waitlist'
    | '/test-404'
    | '/test-error'
    | '/admin/users'
    | '/api/chart-settings'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/go/$slug'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/day-trading-data/$'
    | '/api/e2e/users'
    | '/api/play-data/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/blog/p/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/crypto-trading-simulator'
    | '/day-trading-simulator'
    | '/forex-trading-simulator'
    | '/intraday-trading-practice'
    | '/languages'
    | '/manifest.json'
    | '/market-replay'
    | '/play'
    | '/privacy-policy'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/user-agreement'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/ai'
    | '/changelog'
    | '/contact'
    | '/pricing'
    | '/roadmap'
    | '/waitlist'
    | '/test-404'
    | '/test-error'
    | '/admin/users'
    | '/api/chart-settings'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/go/$slug'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/settings'
    | '/api/auth/$'
    | '/api/day-trading-data/$'
    | '/api/e2e/users'
    | '/api/play-data/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/blog/p/$page'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/crypto-trading-simulator'
    | '/dashboard'
    | '/day-trading-simulator'
    | '/forex-trading-simulator'
    | '/intraday-trading-practice'
    | '/languages'
    | '/manifest.json'
    | '/market-replay'
    | '/play'
    | '/privacy-policy'
    | '/resources'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/user-agreement'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/(pages)/about'
    | '/(pages)/ai'
    | '/(pages)/changelog'
    | '/(pages)/contact'
    | '/(pages)/pricing'
    | '/(pages)/roadmap'
    | '/(pages)/waitlist'
    | '/(tests)/test-404'
    | '/(tests)/test-error'
    | '/admin/users'
    | '/api/chart-settings'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/go/$slug'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/day-trading-data/$'
    | '/api/e2e/users'
    | '/api/play-data/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/blog/p/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CryptoTradingSimulatorRoute: typeof CryptoTradingSimulatorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DayTradingSimulatorRoute: typeof DayTradingSimulatorRoute
  ForexTradingSimulatorRoute: typeof ForexTradingSimulatorRoute
  IntradayTradingPracticeRoute: typeof IntradayTradingPracticeRoute
  LanguagesRoute: typeof LanguagesRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  MarketReplayRoute: typeof MarketReplayRoute
  PlayRoute: typeof PlayRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UserAgreementRoute: typeof UserAgreementRoute
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  pagesAboutRoute: typeof pagesAboutRoute
  pagesAiRoute: typeof pagesAiRoute
  pagesChangelogRoute: typeof pagesChangelogRoute
  pagesContactRoute: typeof pagesContactRoute
  pagesPricingRoute: typeof pagesPricingRoute
  pagesRoadmapRoute: typeof pagesRoadmapRoute
  pagesWaitlistRoute: typeof pagesWaitlistRoute
  testsTest404Route: typeof testsTest404Route
  testsTestErrorRoute: typeof testsTestErrorRoute
  ApiChartSettingsRoute: typeof ApiChartSettingsRoute
  ApiPingRoute: typeof ApiPingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDayTradingDataSplatRoute: typeof ApiDayTradingDataSplatRoute
  ApiE2eUsersRoute: typeof ApiE2eUsersRoute
  ApiPlayDataSplatRoute: typeof ApiPlayDataSplatRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiWebhooksCreemRoute: typeof ApiWebhooksCreemRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  BlogPPageRoute: typeof BlogPPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto-trading-simulator': {
      id: '/crypto-trading-simulator'
      path: '/crypto-trading-simulator'
      fullPath: '/crypto-trading-simulator'
      preLoaderRoute: typeof CryptoTradingSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-trading-simulator': {
      id: '/day-trading-simulator'
      path: '/day-trading-simulator'
      fullPath: '/day-trading-simulator'
      preLoaderRoute: typeof DayTradingSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forex-trading-simulator': {
      id: '/forex-trading-simulator'
      path: '/forex-trading-simulator'
      fullPath: '/forex-trading-simulator'
      preLoaderRoute: typeof ForexTradingSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intraday-trading-practice': {
      id: '/intraday-trading-practice'
      path: '/intraday-trading-practice'
      fullPath: '/intraday-trading-practice'
      preLoaderRoute: typeof IntradayTradingPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-replay': {
      id: '/market-replay'
      path: '/market-replay'
      fullPath: '/market-replay'
      preLoaderRoute: typeof MarketReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-agreement': {
      id: '/user-agreement'
      path: '/user-agreement'
      fullPath: '/user-agreement'
      preLoaderRoute: typeof UserAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/about': {
      id: '/(pages)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof pagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/ai': {
      id: '/(pages)/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof pagesAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/changelog': {
      id: '/(pages)/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof pagesChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/contact': {
      id: '/(pages)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof pagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/pricing': {
      id: '/(pages)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof pagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/roadmap': {
      id: '/(pages)/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof pagesRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/waitlist': {
      id: '/(pages)/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof pagesWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/test-404': {
      id: '/(tests)/test-404'
      path: '/test-404'
      fullPath: '/test-404'
      preLoaderRoute: typeof testsTest404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/test-error': {
      id: '/(tests)/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof testsTestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chart-settings': {
      id: '/api/chart-settings'
      path: '/api/chart-settings'
      fullPath: '/api/chart-settings'
      preLoaderRoute: typeof ApiChartSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/day-trading-data/$': {
      id: '/api/day-trading-data/$'
      path: '/api/day-trading-data/$'
      fullPath: '/api/day-trading-data/$'
      preLoaderRoute: typeof ApiDayTradingDataSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/users': {
      id: '/api/e2e/users'
      path: '/api/e2e/users'
      fullPath: '/api/e2e/users'
      preLoaderRoute: typeof ApiE2eUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/play-data/$': {
      id: '/api/play-data/$'
      path: '/api/play-data/$'
      fullPath: '/api/play-data/$'
      preLoaderRoute: typeof ApiPlayDataSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/creem': {
      id: '/api/webhooks/creem'
      path: '/api/webhooks/creem'
      fullPath: '/api/webhooks/creem'
      preLoaderRoute: typeof ApiWebhooksCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/p/$page': {
      id: '/blog/p/$page'
      path: '/blog/p/$page'
      fullPath: '/blog/p/$page'
      preLoaderRoute: typeof BlogPPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CryptoTradingSimulatorRoute: CryptoTradingSimulatorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DayTradingSimulatorRoute: DayTradingSimulatorRoute,
  ForexTradingSimulatorRoute: ForexTradingSimulatorRoute,
  IntradayTradingPracticeRoute: IntradayTradingPracticeRoute,
  LanguagesRoute: LanguagesRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  MarketReplayRoute: MarketReplayRoute,
  PlayRoute: PlayRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UserAgreementRoute: UserAgreementRoute,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  pagesAboutRoute: pagesAboutRoute,
  pagesAiRoute: pagesAiRoute,
  pagesChangelogRoute: pagesChangelogRoute,
  pagesContactRoute: pagesContactRoute,
  pagesPricingRoute: pagesPricingRoute,
  pagesRoadmapRoute: pagesRoadmapRoute,
  pagesWaitlistRoute: pagesWaitlistRoute,
  testsTest404Route: testsTest404Route,
  testsTestErrorRoute: testsTestErrorRoute,
  ApiChartSettingsRoute: ApiChartSettingsRoute,
  ApiPingRoute: ApiPingRoute,
  BlogSlugRoute: BlogSlugRoute,
  GoSlugRoute: GoSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDayTradingDataSplatRoute: ApiDayTradingDataSplatRoute,
  ApiE2eUsersRoute: ApiE2eUsersRoute,
  ApiPlayDataSplatRoute: ApiPlayDataSplatRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiWebhooksCreemRoute: ApiWebhooksCreemRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  BlogPPageRoute: BlogPPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
