/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as MinecraftSkinViewerRouteImport } from './routes/minecraft-skin-viewer'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const MinecraftSkinViewerRoute = MinecraftSkinViewerRouteImport.update({
  id: '/minecraft-skin-viewer',
  path: '/minecraft-skin-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/minecraft-skin-viewer': typeof MinecraftSkinViewerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/minecraft-skin-viewer': typeof MinecraftSkinViewerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/minecraft-skin-viewer': typeof MinecraftSkinViewerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manifest.json'
    | '/minecraft-skin-viewer'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifest.json'
    | '/minecraft-skin-viewer'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/manifest.json'
    | '/minecraft-skin-viewer'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  MinecraftSkinViewerRoute: typeof MinecraftSkinViewerRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minecraft-skin-viewer': {
      id: '/minecraft-skin-viewer'
      path: '/minecraft-skin-viewer'
      fullPath: '/minecraft-skin-viewer'
      preLoaderRoute: typeof MinecraftSkinViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  MinecraftSkinViewerRoute: MinecraftSkinViewerRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
